services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task_api_frankenphp
    restart: unless-stopped
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:80"
    networks:
      - task_network   # db ve redis ile iletişim
      - task-app       # frontend container'ının ulaşması için
    depends_on:
      - db
      - redis

  db:
    image: postgres:16-alpine
    container_name: task_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - task_network

  redis:
    image: redis:7-alpine
    container_name: task_redis
    restart: unless-stopped
    networks:
      - task_network

  meilisearch:
    image: getmeili/meilisearch:v1.6
    container_name: task_search
    restart: unless-stopped
    environment:
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
    networks:
      - task_network

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task_worker
    restart: unless-stopped
    command: php artisan queue:work --tries=3 --timeout=90
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    networks:
      - task_network

networks:
  task_network:
    driver: bridge
  task-app:
    external: true   # docker network create task-app ile önceden oluşturulmalı

volumes:
  pgdata:
