; OPcache Production
; FrankenPHP + Laravel Octane

[opcache]
opcache.enable=1
opcache.enable_cli=1

; minumum script
opcache.max_accelerated_files=20000

; OPcache (MB)
opcache.memory_consumption=256

; String internment (MB)
opcache.interned_strings_buffer=16

; Dosya değişikliği kontrolü — production'da kapat (performans)
; Development'ta 1 yapılabilir
opcache.validate_timestamps=0

; Bytecode revalidation — validate_timestamps=1
opcache.revalidate_freq=0

opcache.jit=tracing
opcache.jit_buffer_size=128M
